language: scala

env:
  global:
    - PUBLISH_JDK=openjdk8 # admin/build.sh only publishes when running on this jdk
# Don't commit sensitive files, instead commit a version encrypted with $SECRET,
# this environment variable is encrypted with this repo's private key and stored below:
# (See http://docs.travis-ci.com/user/environment-variables/#Secure-Variables.)
    - secure: "apmuVagS7WgWzg9HeDLCcX4INxazi50qukOfPkvluJjm58RCJsDwaZseXrQGqyPzRKuBnAetJ4NDWbZMRkm6QpTiH8grPwDl6iNUSVivvzOZGl3Iy8LvNxUv6CYoQBG+R7d8dW//1xcoHtT2zYo3dYEFpSelfNMMLADNUKXSQmI="

before_install:
  - sudo hostname "$(hostname | cut -c1-63)"
script:
  - admin/build.sh
scala:
  - 2.11.8
  - 2.12.0-M4
jdk:
  - openjdk6
  - oraclejdk8
matrix:
  exclude:
    - scala: 2.12.0-M4
      jdk: openjdk6
notifications:
  email:
    - adriaan.moors@typesafe.com
